# Takes DNA string and returns a RNA string
def Transcribe(DNA):
    RNA = ''
    for base in DNA:
        if base == 'T':
            RNA += 'U'
        elif base == 'G':
            RNA += 'G'
        elif base == 'C':
            RNA += 'C'
        elif base == 'A':
            RNA += 'A'
    return RNA

print(Transcribe("CTCCCGTCGTCGCTGTTGTCGTTACCCTGTTGATCCGTCTTACGACTCAAGCAAAATAACTAAAGGGTAGGTAACCTCTTTGTAAACTGCATCAGTCGATAAGTATATGTCGAAGGGCCTTATTCAATGTTAGGAAATAGGCTAAATCTGCGGAGAGACGTACGCGTTATGTCTTGCCTTCCTTTCGTGTCCCAACGGCGGGGCTGAACGGTACAAATTGTGGTCGGGGAGAGAGGCACCCGTATGCTGTACGTCGGGGGCCAGAATCTATGCTCTCGGCGGTGCCCGGCATACTTGTTGCTCGAGGTAAAACAGGAGTAACGTTGCCCACCCCACAGCTGTCCTCATGGGTTAAATAGGAGTGGTTATTCCTCGGTACTATTCGAGCAGAAGATCACTGACTACGTGACATGCGCGGACCTACACACTCTCGCTACCCTCTCAGGTAAGAGTGAAGGGATCACTCCTCGAACCCCTCATCGCGGACCCTCTGACGGTAAGACGTTCACAAAAGTTCGATAGCCTCGTGGTCCAACTTGCATAACGAAAAGCAGCGCTTACATCAGTTGCGTGGGTGCGGGCTCTGGACTGGCAATCGACAGTCTTGGTGGTACCGATCGAGGAATCAAAAGTCGCCAGAGTAATTGATCGAACTTATATCTGTTGCCACATGATAATAGTGGTGCCTTGTTGTGCCTTCGAGACCACATTGCGGATGCAACCTAGGTGAGCTCGCCAGTATCGCCACTCCCACATTTACCGTTTTCAGTATGTAGTGGGACACTTGGTAGGCCGCGCGAAAGAGAGTCGGGCAGCGATCTGCACGATAACTCTTGTTAAACGCGGGTCATGCCCGGTCCTCAACGCACTCGTTCCCTCTTCACTGCACGATCTTAGCGACACAATCCCGTTCCGCACGTTTCGAGGATTAATACGGTCAGTGGGGGTATTTAGATTTAGATGT"))